<?php
//hepati viral bc
//**************************************VARIABLE*************************************************************//
//**************************************VARIABLE*************************************************************//
// $IDON=$_GET["idon"];
// $IDP=$_GET["IDP"];
// $nomdnr=$_GET["nomdnr"];
// $prenomdnr=$_GET["prenomdnr"];
// $sexe=$_GET["sexe"];
// $DATENAISSANCE=$_GET["DATENAISSANCE"];
// $DATEQUA=$_GET["DATEQUA"];
$datejour=date("d-m-Y");
// $anne=substr($datejour,6,4);
// $x=substr($datejour,6,4);
// $Y=substr($_GET["DATENAISSANCE"],6,4);
// $AGE=$x-$Y;
//*******************FICHE DE TRANSFERT ET DE PRISE EN CHARGE*************************************// 
require('../pdf/dnr.php');
$pdf = new dnr( 'P', 'mm', 'A4' );
$pdf->SetDisplayMode('fullpage','single');//mode d affichage 
$pdf->AddPage('p','A4');
$pdf->SetFont('TIMES','B',12);
$pdf->Text(45,15,"REPUBLIQUE ALGERIENNE DEMOCRATIQUE ET POPULAIRE   ");
$pdf->Text(20,20,"MINSTERE DE LA SANTE DE LA POPUALATION ET DE LA REFORME HOSPITALIERE ");
$pdf->Text(30,25,"DIRECTION DE LA SANTE DE LA POPULATION DE LA WILAYA DE DJELFA  ");
$pdf->Text(50,30,"ETABLISSEMENT PUBLIC HOSPITALIER AIN OUSSERA  ");
$pdf->SetFont('TIMES','B',16);
$pdf->Text(40,50,"FICHE DE TRANSFERT ET DE PRISE EN CHARGE ");
$pdf->SetFont('TIMES','B',12);

$pdf->Text(5,70,"IDENTIFICATION DE L ETABLISSEMENT : EPH AIN OUSSERA ");
$pdf->Text(5,80,"IDENTIFICATION DU SERVICE : POSTE DE TRANSFUSION SANGUINE  ");
$pdf->Text(70,100," IDENTIFICATION DU MALADE ");
$pdf->Text(5,110,"Nom:");//$pdf->Text(18,110,$nomdnr);
$pdf->Text(84,110,"Prenom:");//$pdf->Text(102,110,$prenomdnr);
$pdf->Text(165,110,"Sexe:");// $pdf->Text(177,110,$sexe);
$pdf->Text(5,120,"fils(fille)de :");
$pdf->Text(84,120,"et de:");
$pdf->Text(5,130,"Ne(e)le: ");
// $pdf->Text(22,130,$DATENAISSANCE);
$pdf->Text(165,130,"Age:");
// $pdf->Text(175,130,$AGE."ans");
$pdf->Text(5,140,"Profession");
$pdf->Text(5,150,"Adresse");
$pdf->Text(5,160,"N Securite sociale");
// $pdf->Text(5,170,"N°du prelevement:".$IDP."/".$anne);
$pdf->Text(76,180," MOTIF DE TRANSFERT ");
$pdf->Text(82,190,"Confirmation HVB");
$pdf->Text(60,220," IDENTIFICATION  DU CENTRE D ACCEUIL");
$pdf->Text(55,230,"Institut Pasteur D algerie Annexe De Sidi Fredj");
$pdf->Text(5,260,"le Medecin ");
$pdf->Text(130,260,"ain oussera le :".$datejour);
$pdf->Text(150,270,"le directeur ");
//**************FICHE DE RENSIEGNEMENTS DES HEPATITES VIRALES B&C*******************************************//
$pdf->AddPage('p','A4');$pdf->Image('../public/IMAGES/photos/ipa.jpg',90,10,15,15,0);
$pdf->Text(15,15,"INSTITUT PASTEUR D ALGERIE   ");$pdf->Text(142,15,"service de virologie humaine  ");
$pdf->Text(25,20,"Annexe de sidi fredj   ");      $pdf->Text(138,20,"laboratoire des hepatites virales  ");
                                                   $pdf->Text(136,25," Tél:021 37 68 50 Fax:021 37 76 47   ");
$pdf->Text(45,35,"FICHE DE RENSIEGNEMENTS DES HEPATITES VIRALES B&C  ");
$pdf->Rect(5,40,202,34,"d");
$pdf->Text(8,45,"identification du patient");        $pdf->Text(80,45,"date:I__I__I____I");$pdf->Text(120,45,"identification du service demandeur");
//$pdf->Text(8,50,"nom et prenom:".$nomdnr.$prenomdnr);$pdf->Text(120,50,"nom du médecin:"."Dr Tiba");
$pdf->Text(8,55,"nom de jeune fille:");              $pdf->Text(120,55,"service:"."Poste De Transfusion Sanguine ");
//$pdf->Text(8,60,"date de naissance:".$DATENAISSANCE);$pdf->Text(120,60,"structure:"."EPH Ain Ousserra");
$pdf->Text(8,65,"etat civil:"."marie(e):O"."-"."célibataire:O");$pdf->Text(120,65,"tel/fax:027/82/21/37 poste 34");
$pdf->Text(8,70,"tel:I___I__I__I__I__I");                             $pdf->Text(120,70,"E-mail:");
$pdf->Text(8,80,"Analyse demandées:"); 
$pdf->Text(8,85,"Renseignements Cliniques:");   
$pdf->Rect(5,90,202,18,"d");
$pdf->Text(8,95,"date de debut de la maladie:I__I__I____I");$pdf->Text(110,95,"date du dernier bilan hépatique:I__I__I____I");
$pdf->Text(8,100,"signes cliniques:");$pdf->Text(110,100,"normal:O");$pdf->Text(140,100,"perturbé:O");
$pdf->Text(8,105,"diagnostic clinique suspecté:");$pdf->Text(110,105,"valeurs des transaminases::I_______I");
$pdf->Rect(5,110,202,170,"d");
$pdf->Text(8,115,"renseignements épidemiologique :");
$pdf->Text(8,125,"hepatite virale C: preciser la periode précédant les symptomes de 2 semaines a 6 mois:");
$pdf->Text(8,130,"hepatite virale B: preciser la periode précédant les symptomes de 6 semaines a 6 mois:");
$pdf->Text(8,140,"est ce que le patient a été:");
$pdf->Text(10,150,"o en contact avec une personne présentant une HV aigue ou chronique (suspectée ou confirmée)?");
$pdf->Text(12,160,"si oui,quel type de contact:");
$pdf->Text(110,160,"sexuelle:O");
$pdf->Text(140,160,"familialle:O");
$pdf->Text(180,160,"autres:O");
$pdf->Text(10,170,"o hémodialisé?");
$pdf->Text(12,180,"si oui preciser la date de la 1ere dialyse:I__I__I____I");
$pdf->Text(140,170,"oui:O");
$pdf->Text(160,170,"non:O");
$pdf->Text(180,170,"ind:O");
$pdf->Text(10,190,"o transfusé?");
$pdf->Text(12,200,"si oui preciser la date de la transfusion:I__I__I____I");
$pdf->Text(140,190,"oui:O");
$pdf->Text(160,190,"non:O");
$pdf->Text(180,190,"ind:O");
$pdf->Text(10,210,"o traité pour une infection sexuellement transmissible?");
$pdf->Text(12,220,"si oui préciser la date du dernier traitement:I__I__I____I");
$pdf->Text(140,210,"oui:O");
$pdf->Text(160,210,"non:O");
$pdf->Text(180,210,"ind:O");
$pdf->Text(10,230,"o recus des soins dentaires ou ORl ou fait des examens invasifs ");
$pdf->Text(12,240,"si oui préciser la date:I__I__I____I ");
$pdf->Text(140,230,"oui:O");
$pdf->Text(160,230,"non:O");
$pdf->Text(180,230,"ind:O");
$pdf->Text(10,250,"o hospitalisé?");
$pdf->Text(12,260,"si oui préciser la date:I__I__I____I  ");
$pdf->Text(140,250,"oui:O");
$pdf->Text(160,250,"non:O");
$pdf->Text(180,250,"ind:O");
$pdf->Text(10,270,"o toxicomanie IV nasale?");
$pdf->Text(140,270,"oui:O");
$pdf->Text(160,270,"non:O");
$pdf->Text(180,270,"ind:O");
$pdf->SetFont('Arial','B',10);
//****************FICHE DE RENSIEGNEMENTS DES HEPATITES VIRALES B&C ******************************************//
$pdf->AddPage('p','A4');$pdf->Image('../public/IMAGES/photos/ipa.jpg',90,10,15,15,0);
$pdf->Text(45,35,"FICHE DE RENSIEGNEMENTS DES HEPATITES VIRALES B&C  ");
$pdf->Rect(5, 40, 200, 136 ,"d");
$pdf->Text(8,50,"le patient travail-t-il dans une structure:");
$pdf->Text(10,60,"o medicale l'exposant directement au sang hummain ?");
$pdf->Text(140,60,"oui:O");
$pdf->Text(160,60,"non:O");
$pdf->Text(180,60,"ind:O");
$pdf->Text(10,70,"o publique ou de secours (pompier,secouriste,etc)?");
$pdf->Text(140,70,"oui:O");
$pdf->Text(160,70,"non:O");
$pdf->Text(180,70,"ind:O");
$pdf->Text(12,80,"si oui combien de fois a-t-il été exposé ? :I____I ");
$pdf->Text(8,90,"le patient a-t-il fait un:");
$pdf->Text(110,90,"sacarification:O");
$pdf->Text(140,90,"percing:O");
$pdf->Text(180,90,"tatouage:O");
$pdf->Text(8,100,"le patient est il vacciné contre l'hepatit B :");
$pdf->Text(140,100,"oui:O");
$pdf->Text(160,100,"non:O");
$pdf->Text(180,100,"ind:O");
$pdf->Text(12,110,"si oui la date de la vaccination: 1er dose:I__I__I____I  2eme dose:I__I__I____I  3eme dose:I__I__I____I  ");
$pdf->Text(8,120,"la femme enceinte a-t-elle été confirmée AGHBS positif pendant la grossesse :");
$pdf->Text(140,120,"oui:O");
$pdf->Text(160,120,"non:O");
$pdf->Text(180,120,"ind:O");
$pdf->Text(12,130,"si oui preciser la date de la contamination de AGHBS :I__I__I____I");
$pdf->Text(8,140,"le nouveau né a-t-il été vacciné :");
$pdf->Text(140,140,"oui:O");
$pdf->Text(160,140,"non:O");
$pdf->Text(180,140,"ind:O");
$pdf->Text(12,150,"si oui la date de la vaccination: 1er dose:I__I__I____I  2eme dose:I__I__I____I  3eme dose:I__I__I____I  ");
$pdf->Text(12,160,"a t il recu des immunoglobuline specifiques HBIG ?");
$pdf->Text(140,160,"oui:O");
$pdf->Text(160,160,"non:O");
$pdf->Text(180,160,"ind:O");
$pdf->Text(12,170,"si oui preciser la date :I__I__I____I  ");
$pdf->Rect(5, 180, 200, 50 ,"d");
$pdf->Text(12,190," NB:si des analyse similaires ont deja été effectuées a l IPA rappeler obligatoirement");
$pdf->Text(12,200," leurs numeros d'ordre ou bien les joindre a la fiche de renseignements");
$pdf->Text(12,210," tout prelevement doit obligatoirement etre acccompazgné d'une fiche de renseignements");
$pdf->Text(12,220," correctement remple ,d'un bon de paiment ou d'une prise en charge du service demandeur.");
$pdf->Text(140,260," le medecin ");
$pdf->Output();
?>
