<?php 
$data = array(
"titre"     => 'Patient: edit', 
"btn"       => 'qua', 
"id"        => $this->user[0]['id'],
"butun"     => 'edit Patient', 
"photos"    => '3.jpg',
"action"    => 'mal/editSave1/'.$this->user[0]['id'],
"DINS"      => date("Y-m-d"),
"HINS"      => date("H:i"),
"NOM"       => $this->user[0]['NOM'],
"PRENOM"    => $this->user[0]['PRENOM'],   
"FILSDE"    => 'xxx',
"SEXE"      => array($this->user[0]['SEX'],"M", "F"),
"DATENS"    => $this->user[0]['DATENAISSANCE'], 
"WILAYAN1"  => $this->user[0]['WILAYA'] ,"WILAYAN2"   => View::nbrtostring('wil','IDWIL',$this->user[0]['WILAYA'],'WILAYAS'),
"COMMUNEN1" => $this->user[0]['COMMUNE'] ,"COMMUNEN2" => View::nbrtostring('com','IDCOM',$this->user[0]['COMMUNE'],'COMMUNE'),
"WILAYAR1"  => $this->user[0]['WILAYAR'],
"WILAYAR2"  => View::nbrtostring('wil','IDWIL',$this->user[0]['WILAYAR'],'WILAYAS'),
"COMMUNER1" => $this->user[0]['COMMUNER'],
"COMMUNER2" => View::nbrtostring('com','IDCOM',$this->user[0]['COMMUNER'],'COMMUNE'),
"ADRESSE1"  => $this->user[0]['ADRESSE'],
"ADRESSE2"  => $this->user[0]['ADRESSE'],
"TEL"       => $this->user[0]['TELEPHONE'],
"TELF"      => '(000) 00-00-00',
"EMAIL"     => 'xxx@xxx.xx',
"GRABO"     => $this->user[0]['GRABO'] ,"GRRH" => $this->user[0]['GRRH'],
"CRH2"      => $this->user[0]['CRH2']  ,"CRH4" => $this->user[0]['CRH4'],
"ERH3"      => $this->user[0]['ERH3']  ,"ERH5" => $this->user[0]['ERH5'],
"KELL1"     => $this->user[0]['KELL1'] ,"KELL2" => $this->user[0]['KELL2'],
"NUM"       => $this->user[0]['NUM'] ,
"valuemed"    => '1' ,
"selectedmed" => 'Medecin' ,
"HVB"         => $this->user[0]['HVB'] ,
"HVC"         => $this->user[0]['HVC'] ,
"HIV"         => $this->user[0]['HIV'] ,
"TPHA"        => $this->user[0]['TPHA'] ,
"x"         => "30",
"y"         => "390"
);
View::datamalade($data);
?>

